### PR TITLE
Lf patch and or

### PR DESCRIPTION
**Pull request by lindsay-fredrick**
Small patch update to address issue 14 (explain and/or vs &/|) and change some syntax stuff throughout the qmd files. I'd like to get this one merged in before I start any major new sections, as it changes the format of the `_quarto.yml` file a bit.

### CODE REVIEW

**Review by swayneh — COMMENTED** [review]
All looks good to me!

**Comment by ateucher** [comment]
In general we should avoid forward references ("There is this thing that we will learn about later") because without seeing the immediate use it will at best be ignored, and at worst might confuse people. But I think this is fine, as long as when we do get there, there is also a backwards reference ("remember when we talked about `and`,`or` etc.. those worked on scalars, and we have different operators to work on vectors (in this case data frame columns)")

**Comment by lindsay-fredrick** [comment]
Well you *did* say to include them here! But yes I agree - I think @swayneh is planning to include the comparison again in his section.

**Comment by ateucher** [comment]
Haha, sorry! I guess that's what comes from reviewing individual pieces out of context/order. It looks good :)

**Pull request merged**
