### PR TITLE
Lf patch install instructions

### PR DESCRIPTION
**Pull request by lindsay-fredrick**
I re-wrote the installing section with _hopefully_ instructions that will actually get python up and running from scratch on someone's government workstation. 

@ateucher do you think you could test run this on Amy's computer? 

I'm also not sure if it is worth writing up instructions for Mac users (and we would need help here, as I know they would be close but not identical to the windows instructions).

### CODE REVIEW

**Comment by ateucher** [comment]
@lindsay-forestell Do you want me to try the instructions using the admin privileges route, or the non-admin?

**Comment by lindsay-fredrick** [comment]
@ateucher oh good question. I think perhaps with non-admin?

**Comment by lindsay-fredrick** [comment]
@ateucher were you able to attempt this install without admin rights? I think if we try that it would be good enough, unless you think you have time for Mac instructions. Just trying to get these last few pages all merged in!

**Comment by ateucher** [comment]
I say merge away, the computer I was going to test on already has python so I think it'd be a bit muddy. I have another tester in mind...

**Comment by lindsay-fredrick** [comment]
Great, I'll merge this in and if you have a chance to test it somewhere that'd be great!

**Pull request merged**
